version: '3'

services:
  redis:
    container_name: cache
    image: 'docker.io/bitnami/redis:6.0-debian-10'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
    expose:
         - 6379
    volumes:
      - redis_data:/bitnami/redis/data

  mongodb:
    image: docker.io/bitnami/mongodb:4.4-debian-10
    environment:
      MONGODB_DATABASE: db-phim
      MONGO_INITDB_ROOT_USERNAME: v_dev
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/bitnami/mongodb

volumes:
  mongodb_data:
    driver: local

  redis_data:
    driver: local